### ISSUE TITLE
[ISSUE] Lately, this has been happening a lot

### ISSUE THREAD

**Issue by abeksis** [jimz011/homekit-infused#26] opened 2020-03-12 06:22 UTC
Lately, this has been happening a lot

`2020-03-12 07:55:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.23011112355344] Client exceeded max pending messages [2]: 512
2020-03-12 07:55:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.23011112355344] Client exceeded max pending messages [2]: 512
`

`2020-03-12 08:23:38 ERROR (MainThread) [frontend.js.latest.202002205] :0:0 Script error.`

**Comment by jimz011** [comment] 2020-03-13 20:50
Yes, something is filling the websocket with messages, this is easily reproducable when going through the views quickly. I am looking for the problem, though this might take a while as I have a lot of code to go through. Id anyone knows what the problem is please notify me.

It might be caused by the amount of templating used and I might need to cut back on it. I will keep working on this!

**Comment by jimz011** [comment] 2020-04-22 18:45
This should be fixed in beta8, create a new issue if this is still persistent in upcoming versions.

**Closed by jimz011** 2020-04-22 18:45 UTC
Labels: bug
